// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["amazon-bedrock"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "amazon-bedrock",
    artifactBasename: "api.js",
  });
}
export const discoverBedrockModels: FacadeModule["discoverBedrockModels"] = ((...args: any[]) =>
  (loadFacadeModule()["discoverBedrockModels"] as any)(...args)) as FacadeModule["discoverBedrockModels"];
export const mergeImplicitBedrockProvider: FacadeModule["mergeImplicitBedrockProvider"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["mergeImplicitBedrockProvider"] as any)(...args)) as FacadeModule["mergeImplicitBedrockProvider"];
export const resetBedrockDiscoveryCacheForTest: FacadeModule["resetBedrockDiscoveryCacheForTest"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resetBedrockDiscoveryCacheForTest"] as any)(...args)) as FacadeModule["resetBedrockDiscoveryCacheForTest"];
export const resolveBedrockConfigApiKey: FacadeModule["resolveBedrockConfigApiKey"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveBedrockConfigApiKey"] as any)(...args)) as FacadeModule["resolveBedrockConfigApiKey"];
export const resolveImplicitBedrockProvider: FacadeModule["resolveImplicitBedrockProvider"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveImplicitBedrockProvider"] as any)(...args)) as FacadeModule["resolveImplicitBedrockProvider"];
