// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["anthropic-vertex"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "anthropic-vertex",
    artifactBasename: "api.js",
  });
}
export const ANTHROPIC_VERTEX_DEFAULT_MODEL_ID: FacadeModule["ANTHROPIC_VERTEX_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["ANTHROPIC_VERTEX_DEFAULT_MODEL_ID"];
export const buildAnthropicVertexProvider: FacadeModule["buildAnthropicVertexProvider"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["buildAnthropicVertexProvider"] as any)(...args)) as FacadeModule["buildAnthropicVertexProvider"];
export const hasAnthropicVertexAvailableAuth: FacadeModule["hasAnthropicVertexAvailableAuth"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["hasAnthropicVertexAvailableAuth"] as any)(...args)) as FacadeModule["hasAnthropicVertexAvailableAuth"];
export const hasAnthropicVertexCredentials: FacadeModule["hasAnthropicVertexCredentials"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["hasAnthropicVertexCredentials"] as any)(...args)) as FacadeModule["hasAnthropicVertexCredentials"];
export const mergeImplicitAnthropicVertexProvider: FacadeModule["mergeImplicitAnthropicVertexProvider"] =
  ((...args: any[]) =>
    (loadFacadeModule()["mergeImplicitAnthropicVertexProvider"] as any)(...args)) as FacadeModule["mergeImplicitAnthropicVertexProvider"];
export const resolveAnthropicVertexClientRegion: FacadeModule["resolveAnthropicVertexClientRegion"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveAnthropicVertexClientRegion"] as any)(...args)) as FacadeModule["resolveAnthropicVertexClientRegion"];
export const resolveAnthropicVertexConfigApiKey: FacadeModule["resolveAnthropicVertexConfigApiKey"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveAnthropicVertexConfigApiKey"] as any)(...args)) as FacadeModule["resolveAnthropicVertexConfigApiKey"];
export const resolveImplicitAnthropicVertexProvider: FacadeModule["resolveImplicitAnthropicVertexProvider"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveImplicitAnthropicVertexProvider"] as any)(...args)) as FacadeModule["resolveImplicitAnthropicVertexProvider"];
export const resolveAnthropicVertexProjectId: FacadeModule["resolveAnthropicVertexProjectId"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveAnthropicVertexProjectId"] as any)(...args)) as FacadeModule["resolveAnthropicVertexProjectId"];
export const resolveAnthropicVertexRegion: FacadeModule["resolveAnthropicVertexRegion"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveAnthropicVertexRegion"] as any)(...args)) as FacadeModule["resolveAnthropicVertexRegion"];
export const resolveAnthropicVertexRegionFromBaseUrl: FacadeModule["resolveAnthropicVertexRegionFromBaseUrl"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveAnthropicVertexRegionFromBaseUrl"] as any)(...args)) as FacadeModule["resolveAnthropicVertexRegionFromBaseUrl"];
