// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["browser"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadActivatedBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadActivatedBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "browser",
    artifactBasename: "runtime-api.js",
  });
}
export const browserHandlers: FacadeModule["browserHandlers"] = createLazyFacadeObjectValue(
  () => loadFacadeModule()["browserHandlers"] as object,
) as FacadeModule["browserHandlers"];
export const createBrowserPluginService: FacadeModule["createBrowserPluginService"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["createBrowserPluginService"] as any)(...args)) as FacadeModule["createBrowserPluginService"];
export const createBrowserTool: FacadeModule["createBrowserTool"] = ((...args: any[]) =>
  (loadFacadeModule()["createBrowserTool"] as any)(...args)) as FacadeModule["createBrowserTool"];
export const handleBrowserGatewayRequest: FacadeModule["handleBrowserGatewayRequest"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["handleBrowserGatewayRequest"] as any)(...args)) as FacadeModule["handleBrowserGatewayRequest"];
export const registerBrowserCli: FacadeModule["registerBrowserCli"] = ((...args: any[]) =>
  (loadFacadeModule()["registerBrowserCli"] as any)(...args)) as FacadeModule["registerBrowserCli"];
