// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["browser-runtime"];
type FacadeModule = FacadeEntry["module"];
export {
  DEFAULT_AI_SNAPSHOT_MAX_CHARS,
  DEFAULT_BROWSER_EVALUATE_ENABLED,
  DEFAULT_OPENCLAW_BROWSER_COLOR,
  DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME,
  DEFAULT_UPLOAD_DIR,
  redactCdpUrl,
  resolveBrowserConfig,
  resolveBrowserControlAuth,
  resolveProfile,
} from "./browser-config.js";
export {
  parseBrowserMajorVersion,
  readBrowserVersion,
  resolveGoogleChromeExecutableForPlatform,
} from "./browser-host-inspection.js";
export { closeTrackedBrowserTabsForSessions, movePathToTrash } from "./browser-maintenance.js";
import {
  createLazyFacadeObjectValue,
  loadActivatedBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadActivatedBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "browser",
    artifactBasename: "runtime-api.js",
  });
}
export const applyBrowserProxyPaths: FacadeModule["applyBrowserProxyPaths"] = ((...args: any[]) =>
  (loadFacadeModule()["applyBrowserProxyPaths"] as any)(...args)) as FacadeModule["applyBrowserProxyPaths"];
export const browserAct: FacadeModule["browserAct"] = ((...args: any[]) =>
  (loadFacadeModule()["browserAct"] as any)(...args)) as FacadeModule["browserAct"];
export const browserArmDialog: FacadeModule["browserArmDialog"] = ((...args: any[]) =>
  (loadFacadeModule()["browserArmDialog"] as any)(...args)) as FacadeModule["browserArmDialog"];
export const browserArmFileChooser: FacadeModule["browserArmFileChooser"] = ((...args: any[]) =>
  (loadFacadeModule()["browserArmFileChooser"] as any)(...args)) as FacadeModule["browserArmFileChooser"];
export const browserCloseTab: FacadeModule["browserCloseTab"] = ((...args: any[]) =>
  (loadFacadeModule()["browserCloseTab"] as any)(...args)) as FacadeModule["browserCloseTab"];
export const browserConsoleMessages: FacadeModule["browserConsoleMessages"] = ((...args: any[]) =>
  (loadFacadeModule()["browserConsoleMessages"] as any)(...args)) as FacadeModule["browserConsoleMessages"];
export const browserCreateProfile: FacadeModule["browserCreateProfile"] = ((...args: any[]) =>
  (loadFacadeModule()["browserCreateProfile"] as any)(...args)) as FacadeModule["browserCreateProfile"];
export const browserDeleteProfile: FacadeModule["browserDeleteProfile"] = ((...args: any[]) =>
  (loadFacadeModule()["browserDeleteProfile"] as any)(...args)) as FacadeModule["browserDeleteProfile"];
export const browserFocusTab: FacadeModule["browserFocusTab"] = ((...args: any[]) =>
  (loadFacadeModule()["browserFocusTab"] as any)(...args)) as FacadeModule["browserFocusTab"];
export const browserHandlers: FacadeModule["browserHandlers"] = createLazyFacadeObjectValue(
  () => loadFacadeModule()["browserHandlers"] as object,
) as FacadeModule["browserHandlers"];
export const browserNavigate: FacadeModule["browserNavigate"] = ((...args: any[]) =>
  (loadFacadeModule()["browserNavigate"] as any)(...args)) as FacadeModule["browserNavigate"];
export const browserOpenTab: FacadeModule["browserOpenTab"] = ((...args: any[]) =>
  (loadFacadeModule()["browserOpenTab"] as any)(...args)) as FacadeModule["browserOpenTab"];
export const browserPdfSave: FacadeModule["browserPdfSave"] = ((...args: any[]) =>
  (loadFacadeModule()["browserPdfSave"] as any)(...args)) as FacadeModule["browserPdfSave"];
export const browserProfiles: FacadeModule["browserProfiles"] = ((...args: any[]) =>
  (loadFacadeModule()["browserProfiles"] as any)(...args)) as FacadeModule["browserProfiles"];
export const browserResetProfile: FacadeModule["browserResetProfile"] = ((...args: any[]) =>
  (loadFacadeModule()["browserResetProfile"] as any)(...args)) as FacadeModule["browserResetProfile"];
export const browserScreenshotAction: FacadeModule["browserScreenshotAction"] = ((...args: any[]) =>
  (loadFacadeModule()["browserScreenshotAction"] as any)(...args)) as FacadeModule["browserScreenshotAction"];
export const browserSnapshot: FacadeModule["browserSnapshot"] = ((...args: any[]) =>
  (loadFacadeModule()["browserSnapshot"] as any)(...args)) as FacadeModule["browserSnapshot"];
export const browserStart: FacadeModule["browserStart"] = ((...args: any[]) =>
  (loadFacadeModule()["browserStart"] as any)(...args)) as FacadeModule["browserStart"];
export const browserStatus: FacadeModule["browserStatus"] = ((...args: any[]) =>
  (loadFacadeModule()["browserStatus"] as any)(...args)) as FacadeModule["browserStatus"];
export const browserStop: FacadeModule["browserStop"] = ((...args: any[]) =>
  (loadFacadeModule()["browserStop"] as any)(...args)) as FacadeModule["browserStop"];
export const browserTabAction: FacadeModule["browserTabAction"] = ((...args: any[]) =>
  (loadFacadeModule()["browserTabAction"] as any)(...args)) as FacadeModule["browserTabAction"];
export const browserTabs: FacadeModule["browserTabs"] = ((...args: any[]) =>
  (loadFacadeModule()["browserTabs"] as any)(...args)) as FacadeModule["browserTabs"];
export const createBrowserControlContext: FacadeModule["createBrowserControlContext"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["createBrowserControlContext"] as any)(...args)) as FacadeModule["createBrowserControlContext"];
export const createBrowserPluginService: FacadeModule["createBrowserPluginService"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["createBrowserPluginService"] as any)(...args)) as FacadeModule["createBrowserPluginService"];
export const createBrowserRouteContext: FacadeModule["createBrowserRouteContext"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["createBrowserRouteContext"] as any)(...args)) as FacadeModule["createBrowserRouteContext"];
export const createBrowserRouteDispatcher: FacadeModule["createBrowserRouteDispatcher"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["createBrowserRouteDispatcher"] as any)(...args)) as FacadeModule["createBrowserRouteDispatcher"];
export const createBrowserRuntimeState: FacadeModule["createBrowserRuntimeState"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["createBrowserRuntimeState"] as any)(...args)) as FacadeModule["createBrowserRuntimeState"];
export const createBrowserTool: FacadeModule["createBrowserTool"] = ((...args: any[]) =>
  (loadFacadeModule()["createBrowserTool"] as any)(...args)) as FacadeModule["createBrowserTool"];
export const definePluginEntry: FacadeModule["definePluginEntry"] = ((...args: any[]) =>
  (loadFacadeModule()["definePluginEntry"] as any)(...args)) as FacadeModule["definePluginEntry"];
export const ensureBrowserControlAuth: FacadeModule["ensureBrowserControlAuth"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["ensureBrowserControlAuth"] as any)(...args)) as FacadeModule["ensureBrowserControlAuth"];
export const getBrowserControlState: FacadeModule["getBrowserControlState"] = ((...args: any[]) =>
  (loadFacadeModule()["getBrowserControlState"] as any)(...args)) as FacadeModule["getBrowserControlState"];
export const getBrowserProfileCapabilities: FacadeModule["getBrowserProfileCapabilities"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["getBrowserProfileCapabilities"] as any)(...args)) as FacadeModule["getBrowserProfileCapabilities"];
export const handleBrowserGatewayRequest: FacadeModule["handleBrowserGatewayRequest"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["handleBrowserGatewayRequest"] as any)(...args)) as FacadeModule["handleBrowserGatewayRequest"];
export const installBrowserAuthMiddleware: FacadeModule["installBrowserAuthMiddleware"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["installBrowserAuthMiddleware"] as any)(...args)) as FacadeModule["installBrowserAuthMiddleware"];
export const installBrowserCommonMiddleware: FacadeModule["installBrowserCommonMiddleware"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["installBrowserCommonMiddleware"] as any)(...args)) as FacadeModule["installBrowserCommonMiddleware"];
export const isPersistentBrowserProfileMutation: FacadeModule["isPersistentBrowserProfileMutation"] =
  ((...args: any[]) =>
    (loadFacadeModule()["isPersistentBrowserProfileMutation"] as any)(...args)) as FacadeModule["isPersistentBrowserProfileMutation"];
export const normalizeBrowserFormField: FacadeModule["normalizeBrowserFormField"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["normalizeBrowserFormField"] as any)(...args)) as FacadeModule["normalizeBrowserFormField"];
export const normalizeBrowserFormFieldValue: FacadeModule["normalizeBrowserFormFieldValue"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["normalizeBrowserFormFieldValue"] as any)(...args)) as FacadeModule["normalizeBrowserFormFieldValue"];
export const normalizeBrowserRequestPath: FacadeModule["normalizeBrowserRequestPath"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["normalizeBrowserRequestPath"] as any)(...args)) as FacadeModule["normalizeBrowserRequestPath"];
export const persistBrowserProxyFiles: FacadeModule["persistBrowserProxyFiles"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["persistBrowserProxyFiles"] as any)(...args)) as FacadeModule["persistBrowserProxyFiles"];
export const registerBrowserCli: FacadeModule["registerBrowserCli"] = ((...args: any[]) =>
  (loadFacadeModule()["registerBrowserCli"] as any)(...args)) as FacadeModule["registerBrowserCli"];
export const registerBrowserRoutes: FacadeModule["registerBrowserRoutes"] = ((...args: any[]) =>
  (loadFacadeModule()["registerBrowserRoutes"] as any)(...args)) as FacadeModule["registerBrowserRoutes"];
export const resolveExistingPathsWithinRoot: FacadeModule["resolveExistingPathsWithinRoot"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveExistingPathsWithinRoot"] as any)(...args)) as FacadeModule["resolveExistingPathsWithinRoot"];
export const resolveRequestedBrowserProfile: FacadeModule["resolveRequestedBrowserProfile"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveRequestedBrowserProfile"] as any)(...args)) as FacadeModule["resolveRequestedBrowserProfile"];
export const runBrowserProxyCommand: FacadeModule["runBrowserProxyCommand"] = ((...args: any[]) =>
  (loadFacadeModule()["runBrowserProxyCommand"] as any)(...args)) as FacadeModule["runBrowserProxyCommand"];
export const startBrowserBridgeServer: FacadeModule["startBrowserBridgeServer"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["startBrowserBridgeServer"] as any)(...args)) as FacadeModule["startBrowserBridgeServer"];
export const startBrowserControlServiceFromConfig: FacadeModule["startBrowserControlServiceFromConfig"] =
  ((...args: any[]) =>
    (loadFacadeModule()["startBrowserControlServiceFromConfig"] as any)(...args)) as FacadeModule["startBrowserControlServiceFromConfig"];
export const stopBrowserBridgeServer: FacadeModule["stopBrowserBridgeServer"] = ((...args: any[]) =>
  (loadFacadeModule()["stopBrowserBridgeServer"] as any)(...args)) as FacadeModule["stopBrowserBridgeServer"];
export const stopBrowserControlService: FacadeModule["stopBrowserControlService"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["stopBrowserControlService"] as any)(...args)) as FacadeModule["stopBrowserControlService"];
export const stopBrowserRuntime: FacadeModule["stopBrowserRuntime"] = ((...args: any[]) =>
  (loadFacadeModule()["stopBrowserRuntime"] as any)(...args)) as FacadeModule["stopBrowserRuntime"];
export const trackSessionBrowserTab: FacadeModule["trackSessionBrowserTab"] = ((...args: any[]) =>
  (loadFacadeModule()["trackSessionBrowserTab"] as any)(...args)) as FacadeModule["trackSessionBrowserTab"];
export const untrackSessionBrowserTab: FacadeModule["untrackSessionBrowserTab"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["untrackSessionBrowserTab"] as any)(...args)) as FacadeModule["untrackSessionBrowserTab"];
export type BrowserBridge = FacadeEntry["types"]["BrowserBridge"];
export type BrowserCreateProfileResult = FacadeEntry["types"]["BrowserCreateProfileResult"];
export type BrowserDeleteProfileResult = FacadeEntry["types"]["BrowserDeleteProfileResult"];
export type BrowserExecutable = FacadeEntry["types"]["BrowserExecutable"];
export type BrowserFormField = FacadeEntry["types"]["BrowserFormField"];
export type BrowserResetProfileResult = FacadeEntry["types"]["BrowserResetProfileResult"];
export type BrowserRouteRegistrar = FacadeEntry["types"]["BrowserRouteRegistrar"];
export type BrowserServerState = FacadeEntry["types"]["BrowserServerState"];
export type BrowserStatus = FacadeEntry["types"]["BrowserStatus"];
export type BrowserTab = FacadeEntry["types"]["BrowserTab"];
export type BrowserTransport = FacadeEntry["types"]["BrowserTransport"];
export type OpenClawPluginApi = FacadeEntry["types"]["OpenClawPluginApi"];
export type OpenClawPluginToolContext = FacadeEntry["types"]["OpenClawPluginToolContext"];
export type OpenClawPluginToolFactory = FacadeEntry["types"]["OpenClawPluginToolFactory"];
export type ProfileStatus = FacadeEntry["types"]["ProfileStatus"];
export type ResolvedBrowserConfig = FacadeEntry["types"]["ResolvedBrowserConfig"];
export type ResolvedBrowserProfile = FacadeEntry["types"]["ResolvedBrowserProfile"];
export type SnapshotResult = FacadeEntry["types"]["SnapshotResult"];
