// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["discord-surface"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "discord",
    artifactBasename: "api.js",
  });
}
export const buildDiscordComponentMessage: FacadeModule["buildDiscordComponentMessage"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["buildDiscordComponentMessage"] as any)(...args)) as FacadeModule["buildDiscordComponentMessage"];
export const collectDiscordStatusIssues: FacadeModule["collectDiscordStatusIssues"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["collectDiscordStatusIssues"] as any)(...args)) as FacadeModule["collectDiscordStatusIssues"];
export const createDiscordActionGate: FacadeModule["createDiscordActionGate"] = ((...args: any[]) =>
  (loadFacadeModule()["createDiscordActionGate"] as any)(...args)) as FacadeModule["createDiscordActionGate"];
export const handleDiscordMessageAction: FacadeModule["handleDiscordMessageAction"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["handleDiscordMessageAction"] as any)(...args)) as FacadeModule["handleDiscordMessageAction"];
export const inspectDiscordAccount: FacadeModule["inspectDiscordAccount"] = ((...args: any[]) =>
  (loadFacadeModule()["inspectDiscordAccount"] as any)(...args)) as FacadeModule["inspectDiscordAccount"];
export const isDiscordExecApprovalApprover: FacadeModule["isDiscordExecApprovalApprover"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["isDiscordExecApprovalApprover"] as any)(...args)) as FacadeModule["isDiscordExecApprovalApprover"];
export const isDiscordExecApprovalClientEnabled: FacadeModule["isDiscordExecApprovalClientEnabled"] =
  ((...args: any[]) =>
    (loadFacadeModule()["isDiscordExecApprovalClientEnabled"] as any)(...args)) as FacadeModule["isDiscordExecApprovalClientEnabled"];
export const listDiscordAccountIds: FacadeModule["listDiscordAccountIds"] = ((...args: any[]) =>
  (loadFacadeModule()["listDiscordAccountIds"] as any)(...args)) as FacadeModule["listDiscordAccountIds"];
export const listDiscordDirectoryGroupsFromConfig: FacadeModule["listDiscordDirectoryGroupsFromConfig"] =
  ((...args: any[]) =>
    (loadFacadeModule()["listDiscordDirectoryGroupsFromConfig"] as any)(...args)) as FacadeModule["listDiscordDirectoryGroupsFromConfig"];
export const listDiscordDirectoryPeersFromConfig: FacadeModule["listDiscordDirectoryPeersFromConfig"] =
  ((...args: any[]) =>
    (loadFacadeModule()["listDiscordDirectoryPeersFromConfig"] as any)(...args)) as FacadeModule["listDiscordDirectoryPeersFromConfig"];
export const looksLikeDiscordTargetId: FacadeModule["looksLikeDiscordTargetId"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["looksLikeDiscordTargetId"] as any)(...args)) as FacadeModule["looksLikeDiscordTargetId"];
export const normalizeDiscordMessagingTarget: FacadeModule["normalizeDiscordMessagingTarget"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["normalizeDiscordMessagingTarget"] as any)(...args)) as FacadeModule["normalizeDiscordMessagingTarget"];
export const normalizeDiscordOutboundTarget: FacadeModule["normalizeDiscordOutboundTarget"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["normalizeDiscordOutboundTarget"] as any)(...args)) as FacadeModule["normalizeDiscordOutboundTarget"];
export const readDiscordComponentSpec: FacadeModule["readDiscordComponentSpec"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["readDiscordComponentSpec"] as any)(...args)) as FacadeModule["readDiscordComponentSpec"];
export const resolveDefaultDiscordAccountId: FacadeModule["resolveDefaultDiscordAccountId"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveDefaultDiscordAccountId"] as any)(...args)) as FacadeModule["resolveDefaultDiscordAccountId"];
export const resolveDiscordAccount: FacadeModule["resolveDiscordAccount"] = ((...args: any[]) =>
  (loadFacadeModule()["resolveDiscordAccount"] as any)(...args)) as FacadeModule["resolveDiscordAccount"];
export const resolveDiscordChannelId: FacadeModule["resolveDiscordChannelId"] = ((...args: any[]) =>
  (loadFacadeModule()["resolveDiscordChannelId"] as any)(...args)) as FacadeModule["resolveDiscordChannelId"];
export const resolveDiscordRuntimeGroupPolicy: FacadeModule["resolveDiscordRuntimeGroupPolicy"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveDiscordRuntimeGroupPolicy"] as any)(...args)) as FacadeModule["resolveDiscordRuntimeGroupPolicy"];
export const resolveDiscordGroupRequireMention: FacadeModule["resolveDiscordGroupRequireMention"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveDiscordGroupRequireMention"] as any)(...args)) as FacadeModule["resolveDiscordGroupRequireMention"];
export const resolveDiscordGroupToolPolicy: FacadeModule["resolveDiscordGroupToolPolicy"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveDiscordGroupToolPolicy"] as any)(...args)) as FacadeModule["resolveDiscordGroupToolPolicy"];
export type DiscordComponentMessageSpec = FacadeEntry["types"]["DiscordComponentMessageSpec"];
export type DiscordProbe = FacadeEntry["types"]["DiscordProbe"];
export type DiscordSendComponents = FacadeEntry["types"]["DiscordSendComponents"];
export type DiscordSendEmbeds = FacadeEntry["types"]["DiscordSendEmbeds"];
export type DiscordSendResult = FacadeEntry["types"]["DiscordSendResult"];
export type DiscordTokenResolution = FacadeEntry["types"]["DiscordTokenResolution"];
export type InspectedDiscordAccount = FacadeEntry["types"]["InspectedDiscordAccount"];
export type ResolvedDiscordAccount = FacadeEntry["types"]["ResolvedDiscordAccount"];
