// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["discord-thread-bindings"];
type FacadeModule = FacadeEntry["module"];
export { unbindThreadBindingsBySessionKey } from "./discord-maintenance.js";
import { loadActivatedBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadActivatedBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "discord",
    artifactBasename: "runtime-api.js",
  });
}
export const autoBindSpawnedDiscordSubagent: FacadeModule["autoBindSpawnedDiscordSubagent"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["autoBindSpawnedDiscordSubagent"] as any)(...args)) as FacadeModule["autoBindSpawnedDiscordSubagent"];
export const createThreadBindingManager: FacadeModule["createThreadBindingManager"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["createThreadBindingManager"] as any)(...args)) as FacadeModule["createThreadBindingManager"];
export const getThreadBindingManager: FacadeModule["getThreadBindingManager"] = ((...args: any[]) =>
  (loadFacadeModule()["getThreadBindingManager"] as any)(...args)) as FacadeModule["getThreadBindingManager"];
export const listThreadBindingsBySessionKey: FacadeModule["listThreadBindingsBySessionKey"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["listThreadBindingsBySessionKey"] as any)(...args)) as FacadeModule["listThreadBindingsBySessionKey"];
export const resolveThreadBindingIdleTimeoutMs: FacadeModule["resolveThreadBindingIdleTimeoutMs"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveThreadBindingIdleTimeoutMs"] as any)(...args)) as FacadeModule["resolveThreadBindingIdleTimeoutMs"];
export const resolveThreadBindingInactivityExpiresAt: FacadeModule["resolveThreadBindingInactivityExpiresAt"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveThreadBindingInactivityExpiresAt"] as any)(...args)) as FacadeModule["resolveThreadBindingInactivityExpiresAt"];
export const resolveThreadBindingMaxAgeExpiresAt: FacadeModule["resolveThreadBindingMaxAgeExpiresAt"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveThreadBindingMaxAgeExpiresAt"] as any)(...args)) as FacadeModule["resolveThreadBindingMaxAgeExpiresAt"];
export const resolveThreadBindingMaxAgeMs: FacadeModule["resolveThreadBindingMaxAgeMs"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveThreadBindingMaxAgeMs"] as any)(...args)) as FacadeModule["resolveThreadBindingMaxAgeMs"];
export const setThreadBindingIdleTimeoutBySessionKey: FacadeModule["setThreadBindingIdleTimeoutBySessionKey"] =
  ((...args: any[]) =>
    (loadFacadeModule()["setThreadBindingIdleTimeoutBySessionKey"] as any)(...args)) as FacadeModule["setThreadBindingIdleTimeoutBySessionKey"];
export const setThreadBindingMaxAgeBySessionKey: FacadeModule["setThreadBindingMaxAgeBySessionKey"] =
  ((...args: any[]) =>
    (loadFacadeModule()["setThreadBindingMaxAgeBySessionKey"] as any)(...args)) as FacadeModule["setThreadBindingMaxAgeBySessionKey"];
export type ThreadBindingManager = FacadeEntry["types"]["ThreadBindingManager"];
export type ThreadBindingRecord = FacadeEntry["types"]["ThreadBindingRecord"];
export type ThreadBindingTargetKind = FacadeEntry["types"]["ThreadBindingTargetKind"];
