// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["google"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "google",
    artifactBasename: "api.js",
  });
}
export const applyGoogleGeminiModelDefault: FacadeModule["applyGoogleGeminiModelDefault"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["applyGoogleGeminiModelDefault"] as any)(...args)) as FacadeModule["applyGoogleGeminiModelDefault"];
export const DEFAULT_GOOGLE_API_BASE_URL: FacadeModule["DEFAULT_GOOGLE_API_BASE_URL"] =
  loadFacadeModule()["DEFAULT_GOOGLE_API_BASE_URL"];
export const GOOGLE_GEMINI_DEFAULT_MODEL: FacadeModule["GOOGLE_GEMINI_DEFAULT_MODEL"] =
  loadFacadeModule()["GOOGLE_GEMINI_DEFAULT_MODEL"];
export const isGoogleGenerativeAiApi: FacadeModule["isGoogleGenerativeAiApi"] = ((...args: any[]) =>
  (loadFacadeModule()["isGoogleGenerativeAiApi"] as any)(...args)) as FacadeModule["isGoogleGenerativeAiApi"];
export const normalizeAntigravityModelId: FacadeModule["normalizeAntigravityModelId"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["normalizeAntigravityModelId"] as any)(...args)) as FacadeModule["normalizeAntigravityModelId"];
export const normalizeGoogleApiBaseUrl: FacadeModule["normalizeGoogleApiBaseUrl"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["normalizeGoogleApiBaseUrl"] as any)(...args)) as FacadeModule["normalizeGoogleApiBaseUrl"];
export const normalizeGoogleGenerativeAiBaseUrl: FacadeModule["normalizeGoogleGenerativeAiBaseUrl"] =
  ((...args: any[]) =>
    (loadFacadeModule()["normalizeGoogleGenerativeAiBaseUrl"] as any)(...args)) as FacadeModule["normalizeGoogleGenerativeAiBaseUrl"];
export const normalizeGoogleModelId: FacadeModule["normalizeGoogleModelId"] = ((...args: any[]) =>
  (loadFacadeModule()["normalizeGoogleModelId"] as any)(...args)) as FacadeModule["normalizeGoogleModelId"];
export const normalizeGoogleProviderConfig: FacadeModule["normalizeGoogleProviderConfig"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["normalizeGoogleProviderConfig"] as any)(...args)) as FacadeModule["normalizeGoogleProviderConfig"];
export const parseGeminiAuth: FacadeModule["parseGeminiAuth"] = ((...args: any[]) =>
  (loadFacadeModule()["parseGeminiAuth"] as any)(...args)) as FacadeModule["parseGeminiAuth"];
export const resolveGoogleGenerativeAiApiOrigin: FacadeModule["resolveGoogleGenerativeAiApiOrigin"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveGoogleGenerativeAiApiOrigin"] as any)(...args)) as FacadeModule["resolveGoogleGenerativeAiApiOrigin"];
export const resolveGoogleGenerativeAiTransport: FacadeModule["resolveGoogleGenerativeAiTransport"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveGoogleGenerativeAiTransport"] as any)(...args)) as FacadeModule["resolveGoogleGenerativeAiTransport"];
export const shouldNormalizeGoogleProviderConfig: FacadeModule["shouldNormalizeGoogleProviderConfig"] =
  ((...args: any[]) =>
    (loadFacadeModule()["shouldNormalizeGoogleProviderConfig"] as any)(...args)) as FacadeModule["shouldNormalizeGoogleProviderConfig"];
export const shouldNormalizeGoogleGenerativeAiProviderConfig: FacadeModule["shouldNormalizeGoogleGenerativeAiProviderConfig"] =
  ((...args: any[]) =>
    (loadFacadeModule()["shouldNormalizeGoogleGenerativeAiProviderConfig"] as any)(...args)) as FacadeModule["shouldNormalizeGoogleGenerativeAiProviderConfig"];
