// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["line-surface"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "line",
    artifactBasename: "runtime-api.js",
  });
}
export const createActionCard: FacadeModule["createActionCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createActionCard"] as any)(...args)) as FacadeModule["createActionCard"];
export const createAgendaCard: FacadeModule["createAgendaCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createAgendaCard"] as any)(...args)) as FacadeModule["createAgendaCard"];
export const createAppleTvRemoteCard: FacadeModule["createAppleTvRemoteCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createAppleTvRemoteCard"] as any)(...args)) as FacadeModule["createAppleTvRemoteCard"];
export const createDeviceControlCard: FacadeModule["createDeviceControlCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createDeviceControlCard"] as any)(...args)) as FacadeModule["createDeviceControlCard"];
export const createEventCard: FacadeModule["createEventCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createEventCard"] as any)(...args)) as FacadeModule["createEventCard"];
export const createImageCard: FacadeModule["createImageCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createImageCard"] as any)(...args)) as FacadeModule["createImageCard"];
export const createInfoCard: FacadeModule["createInfoCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createInfoCard"] as any)(...args)) as FacadeModule["createInfoCard"];
export const createListCard: FacadeModule["createListCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createListCard"] as any)(...args)) as FacadeModule["createListCard"];
export const createMediaPlayerCard: FacadeModule["createMediaPlayerCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createMediaPlayerCard"] as any)(...args)) as FacadeModule["createMediaPlayerCard"];
export const createReceiptCard: FacadeModule["createReceiptCard"] = ((...args: any[]) =>
  (loadFacadeModule()["createReceiptCard"] as any)(...args)) as FacadeModule["createReceiptCard"];
export const LineConfigSchema: FacadeModule["LineConfigSchema"] = createLazyFacadeObjectValue(
  () => loadFacadeModule()["LineConfigSchema"] as object,
) as FacadeModule["LineConfigSchema"];
export const listLineAccountIds: FacadeModule["listLineAccountIds"] = ((...args: any[]) =>
  (loadFacadeModule()["listLineAccountIds"] as any)(...args)) as FacadeModule["listLineAccountIds"];
export const normalizeAccountId: FacadeModule["normalizeAccountId"] = ((...args: any[]) =>
  (loadFacadeModule()["normalizeAccountId"] as any)(...args)) as FacadeModule["normalizeAccountId"];
export const processLineMessage: FacadeModule["processLineMessage"] = ((...args: any[]) =>
  (loadFacadeModule()["processLineMessage"] as any)(...args)) as FacadeModule["processLineMessage"];
export const resolveDefaultLineAccountId: FacadeModule["resolveDefaultLineAccountId"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveDefaultLineAccountId"] as any)(...args)) as FacadeModule["resolveDefaultLineAccountId"];
export const resolveExactLineGroupConfigKey: FacadeModule["resolveExactLineGroupConfigKey"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveExactLineGroupConfigKey"] as any)(...args)) as FacadeModule["resolveExactLineGroupConfigKey"];
export const resolveLineAccount: FacadeModule["resolveLineAccount"] = ((...args: any[]) =>
  (loadFacadeModule()["resolveLineAccount"] as any)(...args)) as FacadeModule["resolveLineAccount"];
export type CardAction = FacadeEntry["types"]["CardAction"];
export type LineChannelData = FacadeEntry["types"]["LineChannelData"];
export type LineConfig = FacadeEntry["types"]["LineConfig"];
export type LineProbeResult = FacadeEntry["types"]["LineProbeResult"];
export type ListItem = FacadeEntry["types"]["ListItem"];
export type ResolvedLineAccount = FacadeEntry["types"]["ResolvedLineAccount"];
