// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["matrix-helper"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "matrix",
    artifactBasename: "api.js",
  });
}
export const findMatrixAccountEntry: FacadeModule["findMatrixAccountEntry"] = ((...args: any[]) =>
  (loadFacadeModule()["findMatrixAccountEntry"] as any)(...args)) as FacadeModule["findMatrixAccountEntry"];
export const getMatrixScopedEnvVarNames: FacadeModule["getMatrixScopedEnvVarNames"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["getMatrixScopedEnvVarNames"] as any)(...args)) as FacadeModule["getMatrixScopedEnvVarNames"];
export const requiresExplicitMatrixDefaultAccount: FacadeModule["requiresExplicitMatrixDefaultAccount"] =
  ((...args: any[]) =>
    (loadFacadeModule()["requiresExplicitMatrixDefaultAccount"] as any)(...args)) as FacadeModule["requiresExplicitMatrixDefaultAccount"];
export const resolveConfiguredMatrixAccountIds: FacadeModule["resolveConfiguredMatrixAccountIds"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveConfiguredMatrixAccountIds"] as any)(...args)) as FacadeModule["resolveConfiguredMatrixAccountIds"];
export const resolveMatrixAccountStorageRoot: FacadeModule["resolveMatrixAccountStorageRoot"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveMatrixAccountStorageRoot"] as any)(...args)) as FacadeModule["resolveMatrixAccountStorageRoot"];
export const resolveMatrixChannelConfig: FacadeModule["resolveMatrixChannelConfig"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveMatrixChannelConfig"] as any)(...args)) as FacadeModule["resolveMatrixChannelConfig"];
export const resolveMatrixCredentialsDir: FacadeModule["resolveMatrixCredentialsDir"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveMatrixCredentialsDir"] as any)(...args)) as FacadeModule["resolveMatrixCredentialsDir"];
export const resolveMatrixCredentialsPath: FacadeModule["resolveMatrixCredentialsPath"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveMatrixCredentialsPath"] as any)(...args)) as FacadeModule["resolveMatrixCredentialsPath"];
export const resolveMatrixDefaultOrOnlyAccountId: FacadeModule["resolveMatrixDefaultOrOnlyAccountId"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveMatrixDefaultOrOnlyAccountId"] as any)(...args)) as FacadeModule["resolveMatrixDefaultOrOnlyAccountId"];
export const resolveMatrixLegacyFlatStoragePaths: FacadeModule["resolveMatrixLegacyFlatStoragePaths"] =
  ((...args: any[]) =>
    (loadFacadeModule()["resolveMatrixLegacyFlatStoragePaths"] as any)(...args)) as FacadeModule["resolveMatrixLegacyFlatStoragePaths"];
