// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["media-understanding-runtime"];
type FacadeModule = FacadeEntry["module"];
import { loadActivatedBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadActivatedBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "media-understanding-core",
    artifactBasename: "runtime-api.js",
  });
}
export const describeImageFile: FacadeModule["describeImageFile"] = ((...args: any[]) =>
  (loadFacadeModule()["describeImageFile"] as any)(...args)) as FacadeModule["describeImageFile"];
export const describeImageFileWithModel: FacadeModule["describeImageFileWithModel"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["describeImageFileWithModel"] as any)(...args)) as FacadeModule["describeImageFileWithModel"];
export const describeVideoFile: FacadeModule["describeVideoFile"] = ((...args: any[]) =>
  (loadFacadeModule()["describeVideoFile"] as any)(...args)) as FacadeModule["describeVideoFile"];
export const runMediaUnderstandingFile: FacadeModule["runMediaUnderstandingFile"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["runMediaUnderstandingFile"] as any)(...args)) as FacadeModule["runMediaUnderstandingFile"];
export const transcribeAudioFile: FacadeModule["transcribeAudioFile"] = ((...args: any[]) =>
  (loadFacadeModule()["transcribeAudioFile"] as any)(...args)) as FacadeModule["transcribeAudioFile"];
export type RunMediaUnderstandingFileParams =
  FacadeEntry["types"]["RunMediaUnderstandingFileParams"];
export type RunMediaUnderstandingFileResult =
  FacadeEntry["types"]["RunMediaUnderstandingFileResult"];
