// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["moonshot"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "moonshot",
    artifactBasename: "api.js",
  });
}
export const applyMoonshotNativeStreamingUsageCompat: FacadeModule["applyMoonshotNativeStreamingUsageCompat"] =
  ((...args: any[]) =>
    (loadFacadeModule()["applyMoonshotNativeStreamingUsageCompat"] as any)(...args)) as FacadeModule["applyMoonshotNativeStreamingUsageCompat"];
export const buildMoonshotProvider: FacadeModule["buildMoonshotProvider"] = ((...args: any[]) =>
  (loadFacadeModule()["buildMoonshotProvider"] as any)(...args)) as FacadeModule["buildMoonshotProvider"];
export const isNativeMoonshotBaseUrl: FacadeModule["isNativeMoonshotBaseUrl"] = ((...args: any[]) =>
  (loadFacadeModule()["isNativeMoonshotBaseUrl"] as any)(...args)) as FacadeModule["isNativeMoonshotBaseUrl"];
export const MOONSHOT_BASE_URL: FacadeModule["MOONSHOT_BASE_URL"] =
  loadFacadeModule()["MOONSHOT_BASE_URL"];
export const MOONSHOT_CN_BASE_URL: FacadeModule["MOONSHOT_CN_BASE_URL"] =
  loadFacadeModule()["MOONSHOT_CN_BASE_URL"];
export const MOONSHOT_DEFAULT_MODEL_ID: FacadeModule["MOONSHOT_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["MOONSHOT_DEFAULT_MODEL_ID"];
export const MOONSHOT_DEFAULT_MODEL_REF: FacadeModule["MOONSHOT_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["MOONSHOT_DEFAULT_MODEL_REF"];
