// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["slack-surface"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "slack",
    artifactBasename: "api.js",
  });
}
export const buildSlackThreadingToolContext: FacadeModule["buildSlackThreadingToolContext"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["buildSlackThreadingToolContext"] as any)(...args)) as FacadeModule["buildSlackThreadingToolContext"];
export const createSlackWebClient: FacadeModule["createSlackWebClient"] = ((...args: any[]) =>
  (loadFacadeModule()["createSlackWebClient"] as any)(...args)) as FacadeModule["createSlackWebClient"];
export const deleteSlackMessage: FacadeModule["deleteSlackMessage"] = ((...args: any[]) =>
  (loadFacadeModule()["deleteSlackMessage"] as any)(...args)) as FacadeModule["deleteSlackMessage"];
export const downloadSlackFile: FacadeModule["downloadSlackFile"] = ((...args: any[]) =>
  (loadFacadeModule()["downloadSlackFile"] as any)(...args)) as FacadeModule["downloadSlackFile"];
export const editSlackMessage: FacadeModule["editSlackMessage"] = ((...args: any[]) =>
  (loadFacadeModule()["editSlackMessage"] as any)(...args)) as FacadeModule["editSlackMessage"];
export const extractSlackToolSend: FacadeModule["extractSlackToolSend"] = ((...args: any[]) =>
  (loadFacadeModule()["extractSlackToolSend"] as any)(...args)) as FacadeModule["extractSlackToolSend"];
export const getSlackMemberInfo: FacadeModule["getSlackMemberInfo"] = ((...args: any[]) =>
  (loadFacadeModule()["getSlackMemberInfo"] as any)(...args)) as FacadeModule["getSlackMemberInfo"];
export const handleSlackHttpRequest: FacadeModule["handleSlackHttpRequest"] = ((...args: any[]) =>
  (loadFacadeModule()["handleSlackHttpRequest"] as any)(...args)) as FacadeModule["handleSlackHttpRequest"];
export const inspectSlackAccount: FacadeModule["inspectSlackAccount"] = ((...args: any[]) =>
  (loadFacadeModule()["inspectSlackAccount"] as any)(...args)) as FacadeModule["inspectSlackAccount"];
export const isSlackInteractiveRepliesEnabled: FacadeModule["isSlackInteractiveRepliesEnabled"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["isSlackInteractiveRepliesEnabled"] as any)(...args)) as FacadeModule["isSlackInteractiveRepliesEnabled"];
export const listEnabledSlackAccounts: FacadeModule["listEnabledSlackAccounts"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["listEnabledSlackAccounts"] as any)(...args)) as FacadeModule["listEnabledSlackAccounts"];
export const listSlackAccountIds: FacadeModule["listSlackAccountIds"] = ((...args: any[]) =>
  (loadFacadeModule()["listSlackAccountIds"] as any)(...args)) as FacadeModule["listSlackAccountIds"];
export const listSlackDirectoryGroupsFromConfig: FacadeModule["listSlackDirectoryGroupsFromConfig"] =
  ((...args: any[]) =>
    (loadFacadeModule()["listSlackDirectoryGroupsFromConfig"] as any)(...args)) as FacadeModule["listSlackDirectoryGroupsFromConfig"];
export const listSlackDirectoryPeersFromConfig: FacadeModule["listSlackDirectoryPeersFromConfig"] =
  ((...args: any[]) =>
    (loadFacadeModule()["listSlackDirectoryPeersFromConfig"] as any)(...args)) as FacadeModule["listSlackDirectoryPeersFromConfig"];
export const listSlackEmojis: FacadeModule["listSlackEmojis"] = ((...args: any[]) =>
  (loadFacadeModule()["listSlackEmojis"] as any)(...args)) as FacadeModule["listSlackEmojis"];
export const listSlackMessageActions: FacadeModule["listSlackMessageActions"] = ((...args: any[]) =>
  (loadFacadeModule()["listSlackMessageActions"] as any)(...args)) as FacadeModule["listSlackMessageActions"];
export const listSlackPins: FacadeModule["listSlackPins"] = ((...args: any[]) =>
  (loadFacadeModule()["listSlackPins"] as any)(...args)) as FacadeModule["listSlackPins"];
export const listSlackReactions: FacadeModule["listSlackReactions"] = ((...args: any[]) =>
  (loadFacadeModule()["listSlackReactions"] as any)(...args)) as FacadeModule["listSlackReactions"];
export const normalizeAllowListLower: FacadeModule["normalizeAllowListLower"] = ((...args: any[]) =>
  (loadFacadeModule()["normalizeAllowListLower"] as any)(...args)) as FacadeModule["normalizeAllowListLower"];
export const parseSlackBlocksInput: FacadeModule["parseSlackBlocksInput"] = ((...args: any[]) =>
  (loadFacadeModule()["parseSlackBlocksInput"] as any)(...args)) as FacadeModule["parseSlackBlocksInput"];
export const recordSlackThreadParticipation: FacadeModule["recordSlackThreadParticipation"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["recordSlackThreadParticipation"] as any)(...args)) as FacadeModule["recordSlackThreadParticipation"];
export const resolveDefaultSlackAccountId: FacadeModule["resolveDefaultSlackAccountId"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveDefaultSlackAccountId"] as any)(...args)) as FacadeModule["resolveDefaultSlackAccountId"];
export const resolveSlackAutoThreadId: FacadeModule["resolveSlackAutoThreadId"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveSlackAutoThreadId"] as any)(...args)) as FacadeModule["resolveSlackAutoThreadId"];
export const resolveSlackGroupRequireMention: FacadeModule["resolveSlackGroupRequireMention"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveSlackGroupRequireMention"] as any)(...args)) as FacadeModule["resolveSlackGroupRequireMention"];
export const resolveSlackRuntimeGroupPolicy: FacadeModule["resolveSlackRuntimeGroupPolicy"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveSlackRuntimeGroupPolicy"] as any)(...args)) as FacadeModule["resolveSlackRuntimeGroupPolicy"];
export const resolveSlackGroupToolPolicy: FacadeModule["resolveSlackGroupToolPolicy"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveSlackGroupToolPolicy"] as any)(...args)) as FacadeModule["resolveSlackGroupToolPolicy"];
export const resolveSlackReplyToMode: FacadeModule["resolveSlackReplyToMode"] = ((...args: any[]) =>
  (loadFacadeModule()["resolveSlackReplyToMode"] as any)(...args)) as FacadeModule["resolveSlackReplyToMode"];
export const sendSlackMessage: FacadeModule["sendSlackMessage"] = ((...args: any[]) =>
  (loadFacadeModule()["sendSlackMessage"] as any)(...args)) as FacadeModule["sendSlackMessage"];
export const pinSlackMessage: FacadeModule["pinSlackMessage"] = ((...args: any[]) =>
  (loadFacadeModule()["pinSlackMessage"] as any)(...args)) as FacadeModule["pinSlackMessage"];
export const reactSlackMessage: FacadeModule["reactSlackMessage"] = ((...args: any[]) =>
  (loadFacadeModule()["reactSlackMessage"] as any)(...args)) as FacadeModule["reactSlackMessage"];
export const readSlackMessages: FacadeModule["readSlackMessages"] = ((...args: any[]) =>
  (loadFacadeModule()["readSlackMessages"] as any)(...args)) as FacadeModule["readSlackMessages"];
export const removeOwnSlackReactions: FacadeModule["removeOwnSlackReactions"] = ((...args: any[]) =>
  (loadFacadeModule()["removeOwnSlackReactions"] as any)(...args)) as FacadeModule["removeOwnSlackReactions"];
export const removeSlackReaction: FacadeModule["removeSlackReaction"] = ((...args: any[]) =>
  (loadFacadeModule()["removeSlackReaction"] as any)(...args)) as FacadeModule["removeSlackReaction"];
export const unpinSlackMessage: FacadeModule["unpinSlackMessage"] = ((...args: any[]) =>
  (loadFacadeModule()["unpinSlackMessage"] as any)(...args)) as FacadeModule["unpinSlackMessage"];
export type InspectedSlackAccount = FacadeEntry["types"]["InspectedSlackAccount"];
export type ResolvedSlackAccount = FacadeEntry["types"]["ResolvedSlackAccount"];
export type SlackProbe = FacadeEntry["types"]["SlackProbe"];
