// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["slack-runtime-surface"];
type FacadeModule = FacadeEntry["module"];
import { loadActivatedBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadActivatedBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "slack",
    artifactBasename: "runtime-api.js",
  });
}
export const handleSlackAction: FacadeModule["handleSlackAction"] = ((...args: any[]) =>
  (loadFacadeModule()["handleSlackAction"] as any)(...args)) as FacadeModule["handleSlackAction"];
export const listSlackDirectoryGroupsLive: FacadeModule["listSlackDirectoryGroupsLive"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["listSlackDirectoryGroupsLive"] as any)(...args)) as FacadeModule["listSlackDirectoryGroupsLive"];
export const listSlackDirectoryPeersLive: FacadeModule["listSlackDirectoryPeersLive"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["listSlackDirectoryPeersLive"] as any)(...args)) as FacadeModule["listSlackDirectoryPeersLive"];
export const monitorSlackProvider: FacadeModule["monitorSlackProvider"] = ((...args: any[]) =>
  (loadFacadeModule()["monitorSlackProvider"] as any)(...args)) as FacadeModule["monitorSlackProvider"];
export const probeSlack: FacadeModule["probeSlack"] = ((...args: any[]) =>
  (loadFacadeModule()["probeSlack"] as any)(...args)) as FacadeModule["probeSlack"];
export const resolveSlackChannelAllowlist: FacadeModule["resolveSlackChannelAllowlist"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveSlackChannelAllowlist"] as any)(...args)) as FacadeModule["resolveSlackChannelAllowlist"];
export const resolveSlackUserAllowlist: FacadeModule["resolveSlackUserAllowlist"] = ((
  ...args: any[]
) =>
  (loadFacadeModule()["resolveSlackUserAllowlist"] as any)(...args)) as FacadeModule["resolveSlackUserAllowlist"];
export const sendMessageSlack: FacadeModule["sendMessageSlack"] = ((...args: any[]) =>
  (loadFacadeModule()["sendMessageSlack"] as any)(...args)) as FacadeModule["sendMessageSlack"];
export type SlackActionContext = FacadeEntry["types"]["SlackActionContext"];
